name: Run tests and upload coverage

on: 
  push

jobs:

  test:
  
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest pytest-cov
          pip install coverage

      - name: Run tests
        run: coverage run -m pytest

